/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller_Institucion;
import Controller.Controller_Subir_Iten;
import Entity.Entity_Documento;
import Entity.Entity_Institucion;
import Entity.Entity_Moneda;
import Entity.Entity_Persona;
import Entity.Entity_Tipo_Comprobante;
import Entity.Entity_Tipo_afectacion;
import Entity.Entity_Venta;
import Entity.Entity_Venta_Producto;
import Function.Function_ShowMessageDialog;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author pro
 */
public class View_Subir_institucion extends javax.swing.JInternalFrame {

    Controller_Institucion modeloE = new Controller_Institucion();
    Entity_Persona persona;
    Entity_Institucion institucion;

    JFileChooser selecArchivo = new JFileChooser();
    File archivo;

    /**
     * Creates new form View_Subir_institucion
     */
    public View_Subir_institucion() {
        initComponents();
        new Controller_Subir_Iten().cbxItem(cbx_item);
        selecArchivo.setFileFilter(new FileNameExtensionFilter("Excel (*.xls)", "xls"));
        //selecArchivo.setFileFilter(new FileNameExtensionFilter("Excel (*.xlsx)", "xlsx"));
        modeloE.tabla_institucion(tabla_lista_institucion,"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnImportar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_subir_institucicion = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_lista_institucion = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnImportar1 = new javax.swing.JButton();
        txt_busqueda = new javax.swing.JTextField();
        cbx_item = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("INSTITUCION");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnImportar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnImportar.setText("IMPORTAR");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        jButton1.setText("EXPORTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(5, 5, 5))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tabla_subir_institucicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_subir_institucicion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton2.setText("ACTUALIZAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("SUBIR INSTITUCION", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tabla_lista_institucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_lista_institucion);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        btnImportar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnImportar1.setText("MOSTRAR TODO");
        btnImportar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportar1ActionPerformed(evt);
            }
        });

        txt_busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_busquedaKeyReleased(evt);
            }
        });

        cbx_item.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_itemItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btnImportar1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbx_item, 0, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnImportar1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(cbx_item)
            .addComponent(txt_busqueda)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton3.setText("ACTUALIZAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ELIMINAR POR ITEN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("LISTA INSTITUCIONES", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        // TODO add your handling code here:

        if (selecArchivo.showDialog(null, "Seleccionar archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = selecArchivo.getSelectedFile();
            if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
                //modeloE.Importar(archivo); 
                modeloE.Subir_institucion(tabla_subir_institucicion, archivo);
                /* JOptionPane.showMessageDialog(null,
                       
                    modeloE.Importar(archivo) + "\n Formato ." + archivo.getName().substring(archivo.getName().lastIndexOf(".") + 1),
                    "IMPORTAR EXCEL", JOptionPane.INFORMATION_MESSAGE);*/
            } else {
                JOptionPane.showMessageDialog(null, "Elija un formato valido.");
            }
        }
    }//GEN-LAST:event_btnImportarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            modeloE.exportarExcel1(tabla_subir_institucicion);
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int tabla = 0;
        if (tabla > 0) {
            return;

        }
        tabla_subir_institucicion.editCellAt(0, 0);
        Component aComp = tabla_subir_institucicion.getEditorComponent();
        aComp.requestFocus();

        for (int i = 0; i < tabla_subir_institucicion.getRowCount(); i++) {
            String codigo_modular="";
             if (tabla_subir_institucicion.getValueAt(i, 7).toString().length() == 8) {
                codigo_modular=("" + tabla_subir_institucicion.getValueAt(i, 7));//cliente_numero_de_documento
            } else if (tabla_subir_institucicion.getValueAt(i, 7).toString().length() == 7) {
                codigo_modular=("0" + tabla_subir_institucicion.getValueAt(i, 7));//cliente_numero_de_documento
            } else if (tabla_subir_institucicion.getValueAt(i, 7).toString().length() == 6) {
                codigo_modular=("00" + tabla_subir_institucicion.getValueAt(i, 7));//cliente_numero_de_documento
            } else if (tabla_subir_institucicion.getValueAt(i, 7).toString().length() == 5) {
                codigo_modular=("000" + tabla_subir_institucicion.getValueAt(i, 7));//cliente_numero_de_documento
            } else if (tabla_subir_institucicion.getValueAt(i, 7).toString().length() == 4) {
                codigo_modular=("0000" + tabla_subir_institucicion.getValueAt(i, 7));//cliente_numero_de_documento
            }else{
            codigo_modular=("" +tabla_subir_institucicion.getValueAt(i, 7));
            }
             institucion = new Entity_Institucion(tabla_subir_institucicion.getValueAt(i, 0).toString(), tabla_subir_institucicion.getValueAt(i, 1).toString(),
                    tabla_subir_institucicion.getValueAt(i, 2).toString(), tabla_subir_institucicion.getValueAt(i, 3).toString(),
                    tabla_subir_institucicion.getValueAt(i, 4).toString(), tabla_subir_institucicion.getValueAt(i, 5).toString(),
                    tabla_subir_institucicion.getValueAt(i, 6).toString(), tabla_subir_institucicion.getValueAt(i, 7).toString(),
                    tabla_subir_institucicion.getValueAt(i, 8).toString(), tabla_subir_institucicion.getValueAt(i, 9).toString(),
                    tabla_subir_institucicion.getValueAt(i, 10).toString(), tabla_subir_institucicion.getValueAt(i, 11).toString(),
                    tabla_subir_institucicion.getValueAt(i, 12).toString(), tabla_subir_institucicion.getValueAt(i, 13).toString(),
                    tabla_subir_institucicion.getValueAt(i, 14).toString(), tabla_subir_institucicion.getValueAt(i, 15).toString(),
                    tabla_subir_institucicion.getValueAt(i, 16).toString(), tabla_subir_institucicion.getValueAt(i, 17).toString(),
                    tabla_subir_institucicion.getValueAt(i, 18).toString(), tabla_subir_institucicion.getValueAt(i, 19).toString(),
                    tabla_subir_institucicion.getValueAt(i, 20).toString(), tabla_subir_institucicion.getValueAt(i, 21).toString(),
                    tabla_subir_institucicion.getValueAt(i, 22).toString(), tabla_subir_institucicion.getValueAt(i, 23).toString(),
                    tabla_subir_institucicion.getValueAt(i, 24).toString(), tabla_subir_institucicion.getValueAt(i, 25).toString(),
             "",tabla_subir_institucicion.getValueAt(i, 26).toString());
             
              if (modeloE.Add_institutcion(institucion).equals("exito")) {
                     String codigo=modeloE.generar_cod_proveedor();
             persona=new Entity_Persona(codigo, "2", "",codigo_modular , tabla_subir_institucicion.getValueAt(i, 10).toString(), "",  tabla_subir_institucicion.getValueAt(i, 11).toString(),tabla_subir_institucicion.getValueAt(i, 7).toString());
            modeloE.Add_proveedor(persona);
            if (modeloE.Add_proveedor(persona).equals("exito")) {
                 
                
             
            }else{
             JOptionPane.showMessageDialog(rootPane, "ERROR DE REGISTRO");
             return;
            
            }
                }else{
                 JOptionPane.showMessageDialog(rootPane, "ERROR DE REGISTRO");
             return;
                 }
              
              
           
             
           
            

        }
        JOptionPane.showMessageDialog(rootPane, "EL REGISTRO DE INSTITUCION FUE EXITOSO");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnImportar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportar1ActionPerformed
        // TODO add your handling code here:
        modeloE.tabla_institucion(tabla_lista_institucion,"");
    }//GEN-LAST:event_btnImportar1ActionPerformed

    private void txt_busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedaKeyReleased
        // TODO add your handling code here:
        filtro_tabla(txt_busqueda.getText().toUpperCase(), tabla_lista_institucion);
    }//GEN-LAST:event_txt_busquedaKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int tabla = 0;
        if (tabla > 0) {
            return;

        }
        tabla_lista_institucion.editCellAt(0, 0);
        Component aComp = tabla_lista_institucion.getEditorComponent();
        aComp.requestFocus();

        for (int i = 0; i < tabla_lista_institucion.getRowCount(); i++) {
            
                institucion = new Entity_Institucion(tabla_lista_institucion.getValueAt(i, 0).toString(), tabla_lista_institucion.getValueAt(i, 1).toString(),
                    tabla_lista_institucion.getValueAt(i, 2).toString(), tabla_lista_institucion.getValueAt(i, 3).toString(),
                    tabla_lista_institucion.getValueAt(i, 4).toString(), tabla_lista_institucion.getValueAt(i, 5).toString(),
                    tabla_lista_institucion.getValueAt(i, 6).toString(), tabla_lista_institucion.getValueAt(i, 7).toString(),
                    tabla_lista_institucion.getValueAt(i, 8).toString(), tabla_lista_institucion.getValueAt(i, 9).toString(),
                    tabla_lista_institucion.getValueAt(i, 10).toString(), tabla_lista_institucion.getValueAt(i, 11).toString(),
                    tabla_lista_institucion.getValueAt(i, 12).toString(), tabla_lista_institucion.getValueAt(i, 13).toString(),
                    tabla_lista_institucion.getValueAt(i, 14).toString(), tabla_lista_institucion.getValueAt(i, 15).toString(),
                    tabla_lista_institucion.getValueAt(i, 16).toString(), tabla_lista_institucion.getValueAt(i, 17).toString(),
                    tabla_lista_institucion.getValueAt(i, 18).toString(), tabla_lista_institucion.getValueAt(i, 19).toString(),
                    tabla_lista_institucion.getValueAt(i, 20).toString(), tabla_lista_institucion.getValueAt(i, 21).toString(),
                    tabla_lista_institucion.getValueAt(i, 22).toString(), tabla_lista_institucion.getValueAt(i, 23).toString(),
                    tabla_lista_institucion.getValueAt(i, 24).toString(), tabla_lista_institucion.getValueAt(i, 25).toString(),
                    tabla_lista_institucion.getValueAt(i, 26).toString(),tabla_lista_institucion.getValueAt(i, 27).toString());
                 if (modeloE.Add_institutcion(institucion).equals("exito")) {
                    
                }else{
                 JOptionPane.showMessageDialog(rootPane, "ERROR DE REGISTRO");
             return;
                 }
        }
        JOptionPane.showMessageDialog(rootPane, "EL REGISTRO DE INSTITUCION FUE EXITOSO");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int tabla = 0;
        if (tabla > 0) {
            return;

        }
    
        tabla_lista_institucion.editCellAt(0, 0);
        Component aComp = tabla_lista_institucion.getEditorComponent();
        aComp.requestFocus();

        for (int i = 0; i < tabla_lista_institucion.getRowCount(); i++) {
            String codigo_modular="";
             if (tabla_lista_institucion.getValueAt(i, 7).toString().length() == 8) {
                codigo_modular=("" + tabla_lista_institucion.getValueAt(i, 7));//cliente_numero_de_documento
            } else if (tabla_lista_institucion.getValueAt(i, 7).toString().length() == 7) {
                codigo_modular=("0" + tabla_lista_institucion.getValueAt(i, 7));//cliente_numero_de_documento
            } else if (tabla_lista_institucion.getValueAt(i, 7).toString().length() == 6) {
                codigo_modular=("00" + tabla_lista_institucion.getValueAt(i, 7));//cliente_numero_de_documento
            } else if (tabla_lista_institucion.getValueAt(i, 7).toString().length() == 5) {
                codigo_modular=("000" + tabla_lista_institucion.getValueAt(i, 7));//cliente_numero_de_documento
            } else if (tabla_lista_institucion.getValueAt(i, 7).toString().length() == 4) {
                codigo_modular=("0000" + tabla_lista_institucion.getValueAt(i, 7));//cliente_numero_de_documento
            }else {
                codigo_modular=("" + tabla_lista_institucion.getValueAt(i, 7));//cliente_numero_de_documento
            }
             if (modeloE.delete_institutcion(codigo_modular,tabla_lista_institucion.getValueAt(i, 7).toString()).equals("exito")) {
                 System.out.println("View.View_Subir_institucion.jButton4ActionPerformed()"+codigo_modular);
            }else{
             Function_ShowMessageDialog.ShowMessageDialogvalidacion(aComp, "ERROR NO PUEDO SER ELIMINADO");
             return;
             }
             
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbx_itemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_itemItemStateChanged
        // TODO add your handling code here:
        modeloE.tabla_institucion(tabla_lista_institucion,cbx_item.getSelectedItem().toString());
    }//GEN-LAST:event_cbx_itemItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < tabla_lista_institucion.getRowCount(); i++) {
            tabla_lista_institucion.setValueAt(new Controller_Institucion().editar(tabla_lista_institucion.getValueAt(i,7 ).toString()), i, 24);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

void filtro_tabla(String consulta, JTable jtableBuscar) {
        DefaultTableModel dm = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnImportar;
    public javax.swing.JButton btnImportar1;
    private javax.swing.JComboBox<String> cbx_item;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabla_lista_institucion;
    private javax.swing.JTable tabla_subir_institucicion;
    private javax.swing.JTextField txt_busqueda;
    // End of variables declaration//GEN-END:variables
}
