/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Comprobantes_E_SUNAT.CE_Guia;
import Conexion.Conexion;
import static Config_Class.Read_PDF_From_URL.descargar_pdf;
import static Config_Class.openURL.openURL;
import Controller.Controller_Cardex_fisico;
import Controller.Controller_Cardex_fisico_Lote;
import Entity.Entity_Almacen;
import Entity.Entity_Sunat_transaccion;
import Function.Function_Component;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.FocusManager;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.printing.PDFPageable;

/**
 *
 * @author pro
 */
public class View_Cardex_Fisico_X_LOTE_Personalizado extends javax.swing.JInternalFrame {

    Controller_Cardex_fisico_Lote cardex = new Controller_Cardex_fisico_Lote();

    /**
     * Creates new form View_Cardex_Fisico
     */
    public View_Cardex_Fisico_X_LOTE_Personalizado() {
        initComponents();
        Date date = new Date();

        datefecha3.setDate(date);
        datefecha1.setDate(date);
        datefecha2.setDate(date);
        txt_id_producto1.setEditable(false);
        txt_descripcion1.setEditable(false);
        txt_fecha_ven.setEditable(false);
        Function_Component.JButton(jButton1);
        Function_Component.JButton(jButton2);
        Function_Component.JButton(jButton3);
        Function_Component.JButton(jButton4);
        Function_Component.JButton(jButton5);
        Function_Component.JDateChooser(datefecha1);
        Function_Component.JDateChooser(datefecha2);
        Function_Component.JDateChooser(datefecha3);
        Function_Component.JTextField(txt_id_producto1);
        Function_Component.JTextField(txt_lote);
        Function_Component.JTextField(txt_fecha_ven);
        Function_Component.JTextField(txt_descripcion1);
        // mascara.setPlaceholderCharacter("AAAA-MM-DD");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_producto = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txt_busqueda_producto = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_pruducto = new javax.swing.JTable();
        Dialog_seguimiento = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        txt_busqueda_producto1 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_pruducto1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_lote = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_descripcion1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_id_producto1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        datefecha2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        datefecha3 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        datefecha1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txt_fecha_ven = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_cardex = new javax.swing.JTable();

        Dialog_producto.setTitle("PRODUCTO");
        Dialog_producto.setAutoRequestFocus(false);
        Dialog_producto.setMinimumSize(new java.awt.Dimension(1101, 406));
        Dialog_producto.setModal(true);
        Dialog_producto.setResizable(false);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        txt_busqueda_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_busqueda_productoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_busqueda_producto)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(txt_busqueda_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        tabla_pruducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_pruducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_pruductoMouseClicked(evt);
            }
        });
        tabla_pruducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_pruductoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_pruducto);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Dialog_productoLayout = new javax.swing.GroupLayout(Dialog_producto.getContentPane());
        Dialog_producto.getContentPane().setLayout(Dialog_productoLayout);
        Dialog_productoLayout.setHorizontalGroup(
            Dialog_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_productoLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        Dialog_productoLayout.setVerticalGroup(
            Dialog_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Dialog_seguimiento.setTitle("SEGUIMIENTO");
        Dialog_seguimiento.setAutoRequestFocus(false);
        Dialog_seguimiento.setMaximumSize(new java.awt.Dimension(1213, 386));
        Dialog_seguimiento.setMinimumSize(new java.awt.Dimension(1213, 386));
        Dialog_seguimiento.setModal(true);
        Dialog_seguimiento.setResizable(false);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        txt_busqueda_producto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_busqueda_producto1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_busqueda_producto1)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(txt_busqueda_producto1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        tabla_pruducto1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_pruducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_pruducto1MouseClicked(evt);
            }
        });
        tabla_pruducto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_pruducto1KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tabla_pruducto1);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Dialog_seguimientoLayout = new javax.swing.GroupLayout(Dialog_seguimiento.getContentPane());
        Dialog_seguimiento.getContentPane().setLayout(Dialog_seguimientoLayout);
        Dialog_seguimientoLayout.setHorizontalGroup(
            Dialog_seguimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_seguimientoLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        Dialog_seguimientoLayout.setVerticalGroup(
            Dialog_seguimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_seguimientoLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CARDEX FISICO X  LOTE PERSONALIZADO");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txt_lote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loteActionPerformed(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("LOTE DE PRODUCTO");

        jLabel3.setText("Fecha de inicio de almacen");

        datefecha2.setDateFormatString("dd-MM-yyyy");
        datefecha2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datefecha2KeyPressed(evt);
            }
        });

        jLabel7.setText("Fecha de fin de salida");

        datefecha3.setDateFormatString("dd-MM-yyyy");

        jLabel4.setText("Fecha para la muestra del stock ");

        datefecha1.setDateFormatString("dd-MM-yyyy");
        datefecha1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datefecha1KeyPressed(evt);
            }
        });

        jButton2.setText("FILTRAR X EMPRESA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("FILTRAR TODO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txt_fecha_ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha_venActionPerformed(evt);
            }
        });

        jLabel2.setText("FECHA DE VENCIMIENTO");

        jLabel5.setText("DESCRIPCION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txt_id_producto1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_lote)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                    .addComponent(datefecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(datefecha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(datefecha3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_fecha_ven, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_descripcion1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_fecha_ven, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_lote, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_id_producto1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(datefecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datefecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datefecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton3.setText("CONSOLIDADO KARDEX");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("KARDEX X  EMPRESA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tabla_cardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_cardex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_cardexMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_cardex);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Conexion cxn = new Conexion();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        try {

            String delte = "truncate table reporte_cadex_lote_temporal";
            cxn.conectardb().createStatement().executeUpdate(delte);
            for (int i = 0; i < tabla_cardex.getRowCount(); i++) {
                String sql = "insert into reporte_cadex_lote_temporal(reporte_fecha,reporte_entrada,reporte_salida,reporte_saldo,reporte_motivo,reporte_responsable,reporte_observacion,reporte_lote)values("
                        + "'" + tabla_cardex.getValueAt(i, 0).toString() + "','" + tabla_cardex.getValueAt(i, 1).toString() + "','" + tabla_cardex.getValueAt(i, 2).toString() + "','" + tabla_cardex.getValueAt(i, 3).toString() + "',"
                        + "'" + tabla_cardex.getValueAt(i, 4).toString() + "','" + tabla_cardex.getValueAt(i, 5).toString() + "','" + tabla_cardex.getValueAt(i, 6).toString() + "','" + txt_lote.getText() + "')";
                cxn.conectardb().createStatement().executeUpdate(sql);
                cxn.desconectar();

            }
        } catch (SQLException ex) {
            Logger.getLogger(View_Cardex_Fisico_X_LOTE_Personalizado.class.getName()).log(Level.SEVERE, null, ex);
        }
        Map p = new HashMap();
        p.put("lote", txt_lote.getText());
        p.put("fecha_1", f.format(datefecha2.getDate()));
        p.put("fecha_2", f.format(datefecha3.getDate()));
        p.put("producto_id", txt_id_producto1.getText());
        p.put("fecha_vencimiento", txt_fecha_ven.getText());

        try {
            JasperReport report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                    + "\\src\\Reportes\\report.jrxml");
            JasperPrint print;
            print = JasperFillManager.fillReport(report, p, cxn.conectardb());
            JasperViewer view = new JasperViewer(print, false);
            view.setTitle("STOCK");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void datefecha2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datefecha2KeyPressed
        // TODO add your handling code here:
        /* if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("View.View_Ingreso_Productos.date_fecha_emisionKeyPressed()");

        }*/
    }//GEN-LAST:event_datefecha2KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Conexion cxn = new Conexion();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        try {

            String delte = "truncate table reporte_cadex_lote_temporal";
            cxn.conectardb().createStatement().executeUpdate(delte);
            for (int i = 0; i < tabla_cardex.getRowCount(); i++) {
                String sql = "insert into reporte_cadex_lote_temporal(reporte_fecha,reporte_entrada,reporte_salida,reporte_saldo,reporte_motivo,reporte_responsable,reporte_observacion,reporte_lote)values("
                        + "'" + tabla_cardex.getValueAt(i, 0).toString() + "','" + tabla_cardex.getValueAt(i, 1).toString() + "','" + tabla_cardex.getValueAt(i, 2).toString() + "','" + tabla_cardex.getValueAt(i, 3).toString() + "',"
                        + "'" + tabla_cardex.getValueAt(i, 4).toString() + "','" + tabla_cardex.getValueAt(i, 5).toString() + "','" + tabla_cardex.getValueAt(i, 6).toString() + "','" + txt_lote.getText() + "')";
                cxn.conectardb().createStatement().executeUpdate(sql);
                cxn.desconectar();

            }
        } catch (SQLException ex) {
            Logger.getLogger(View_Cardex_Fisico_X_LOTE_Personalizado.class.getName()).log(Level.SEVERE, null, ex);
        }
        Map p = new HashMap();
        p.put("lote", txt_lote.getText());
        p.put("fecha_1", f.format(datefecha2.getDate()));
        p.put("fecha_2", f.format(datefecha3.getDate()));
        p.put("producto_id", txt_id_producto1.getText());
        p.put("empresa", ((Entity_Almacen) View_Escritorio.cbx_almacen.getSelectedItem()).getAlmacen_id());
        p.put("fecha_vencimiento", txt_fecha_ven.getText());

        try {
            JasperReport report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                    + "\\src\\Reportes\\report_x_empresa.jrxml");
            JasperPrint print;
            print = JasperFillManager.fillReport(report, p, cxn.conectardb());
            JasperViewer view = new JasperViewer(print, false);
            view.setTitle("STOCK");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* try {
            Process p = Runtime.getRuntime().exec("C:\\Program Files (x86)\\Jaspersoft\\iReport-5.6.0\\bin\\ireport.exe -C:\\Users\\memo\\Documents\\NetBeansProjects\\ERP_SC_Almacen\\src\\Reportes\\Jaspersoft_Cardex.jasper");
            // Process p2 = Runtime.getRuntime().exec("C:\\Users\\memo\\Documents\\NetBeansProjects\\ERP_SC_Almacen\\src\\Reportes\\Jaspersoft_Cardex.jasper"); 
            p.waitFor();
            //  p2.waitFor(); 
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } catch (InterruptedException ex) {
            Logger.getLogger(View_Cardex_Fisico_X_LOTE_Personalizado.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_busqueda_productoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busqueda_productoKeyReleased
        // TODO add your handling code here:
        // filtro_tabla(txt_busqueda_producto.getText().toUpperCase(), tabla_pruducto);
        filtro_tabla(txt_busqueda_producto.getText().toUpperCase(), tabla_pruducto);
    }//GEN-LAST:event_txt_busqueda_productoKeyReleased

    private void tabla_pruductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_pruductoMouseClicked
        // TODO add your handling code here:
        txt_id_producto1.setText("" + tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 1));
        txt_lote.setText("" + tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 2));
        txt_descripcion1.setText("" + tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 3));
        txt_fecha_ven.setText("" + tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 4));

        /*table_productos_compra.setValueAt(tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 6), table_productos_compra.getSelectedRow() + salida.variable(), 6);
        table_productos_compra.setValueAt(tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 7), table_productos_compra.getSelectedRow() + salida.variable(), 7);
        table_productos_compra.setValueAt(tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 8), table_productos_compra.getSelectedRow() + salida.variable(), 8);
        table_productos_compra.setValueAt(tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 9), table_productos_compra.getSelectedRow() + salida.variable(), 9);
        table_productos_compra.setValueAt(tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 5), table_productos_compra.getSelectedRow() + salida.variable(), 11);
        Dialog_producto.dispose();
        txt_busqueda_producto.setText("");*/
    }//GEN-LAST:event_tabla_pruductoMouseClicked

    private void tabla_pruductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_pruductoKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_id_producto1.setText("" + tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 1));
            txt_lote.setText("" + tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 2));
            txt_descripcion1.setText("" + tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 3));
            txt_fecha_ven.setText("" + tabla_pruducto.getValueAt(tabla_pruducto.getSelectedRow(), 4));
            Dialog_producto.dispose();
            txt_busqueda_producto.setText("");
        }
    }//GEN-LAST:event_tabla_pruductoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_lote.setText("");
        cardex.tabla_producto(tabla_pruducto, txt_lote.getText());
        Dimension desktopSize = View_Escritorio.desktopPane.getSize();
        Dimension FrameSize = Dialog_producto.getSize();
        Dialog_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Dialog_producto.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_busqueda_producto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busqueda_producto1KeyReleased
        // TODO add your handling code here:
        filtro_tabla(txt_busqueda_producto1.getText().toUpperCase(), tabla_pruducto1);
    }//GEN-LAST:event_txt_busqueda_producto1KeyReleased

    private void tabla_pruducto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_pruducto1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tabla_pruducto1MouseClicked

    private void tabla_pruducto1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_pruducto1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tabla_pruducto1KeyPressed

    private void datefecha1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datefecha1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_datefecha1KeyPressed

    private void txt_loteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        String fecha1 = f.format(datefecha1.getDate());
        String fecha2 = f.format(datefecha2.getDate());
        String fecha3 = f.format(datefecha3.getDate());
        cardex.tabla_lote_todo_empresa(tabla_cardex, txt_lote.getText(), fecha1, fecha2, fecha3, txt_fecha_ven.getText(), txt_id_producto1.getText(), ((Entity_Almacen) View_Escritorio.cbx_almacen.getSelectedItem()).getAlmacen_id());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        String fecha1 = f.format(datefecha1.getDate());
        String fecha2 = f.format(datefecha2.getDate());
        String fecha3 = f.format(datefecha3.getDate());
        cardex.tabla_lote_todo(tabla_cardex, txt_lote.getText(), fecha1, fecha2, fecha3, txt_fecha_ven.getText(), txt_id_producto1.getText());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_fecha_venActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha_venActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha_venActionPerformed

    private void tabla_cardexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_cardexMouseClicked
        // TODO add your handling code here:
        int fila = tabla_cardex.rowAtPoint(evt.getPoint());
        int column = tabla_cardex.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tabla_cardex.getRowHeight();
        if (row < tabla_cardex.getRowCount() && row >= 0 && column < tabla_cardex.getColumnCount() && column >= 0) {
            Object value = tabla_cardex.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btnbuscar")) {
                    if (tabla_cardex.getValueAt(tabla_cardex.getSelectedRow(), 4).toString().equals("DISTRIBUCION")) {
                        cardex.table_venta_distribucion(tabla_pruducto1, tabla_cardex.getValueAt(tabla_cardex.getSelectedRow(), 0).toString(), txt_lote.getText(), txt_fecha_ven.getText(), txt_id_producto1.getText(), tabla_cardex.getValueAt(tabla_cardex.getSelectedRow(), 8).toString());
                        Dimension desktopSize = View_Escritorio.desktopPane.getSize();
                        Dimension FrameSize = Dialog_seguimiento.getSize();
                        Dialog_seguimiento.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
                        Dialog_seguimiento.setVisible(true);
                    } else if (tabla_cardex.getValueAt(tabla_cardex.getSelectedRow(), 4).toString().equals("INGRESO ALMACEN")) {
                        cardex.table_venta_compra(tabla_pruducto1, tabla_cardex.getValueAt(tabla_cardex.getSelectedRow(), 0).toString(), txt_lote.getText(), txt_fecha_ven.getText(), txt_id_producto1.getText(), tabla_cardex.getValueAt(tabla_cardex.getSelectedRow(), 8).toString());
                        Dimension desktopSize = View_Escritorio.desktopPane.getSize();
                        Dimension FrameSize = Dialog_seguimiento.getSize();
                        Dialog_seguimiento.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
                        Dialog_seguimiento.setVisible(true);

                    } else if (tabla_cardex.getValueAt(tabla_cardex.getSelectedRow(), 4).toString().equals("ALMACEN")) {
                        cardex.table_venta_compra(tabla_pruducto1, tabla_cardex.getValueAt(tabla_cardex.getSelectedRow(), 0).toString(), txt_lote.getText(), txt_fecha_ven.getText(), txt_id_producto1.getText(), tabla_cardex.getValueAt(tabla_cardex.getSelectedRow(), 8).toString());
                        Dimension desktopSize = View_Escritorio.desktopPane.getSize();
                        Dimension FrameSize = Dialog_seguimiento.getSize();
                        Dialog_seguimiento.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
                        Dialog_seguimiento.setVisible(true);
                        
                        
                    } else {

                        cardex.table_venta(tabla_pruducto1, tabla_cardex.getValueAt(tabla_cardex.getSelectedRow(), 0).toString(), txt_lote.getText(), txt_fecha_ven.getText(), txt_id_producto1.getText(), tabla_cardex.getValueAt(tabla_cardex.getSelectedRow(), 8).toString());
                        Dimension desktopSize = View_Escritorio.desktopPane.getSize();
                        Dimension FrameSize = Dialog_seguimiento.getSize();
                        Dialog_seguimiento.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
                        Dialog_seguimiento.setVisible(true);

                    }

                }
                if (value instanceof JCheckBox) {
                    //((JCheckBox)value).doClick();
                    JCheckBox ch = (JCheckBox) value;
                    if (ch.isSelected() == true) {
                        ch.setSelected(false);
                    }
                    if (ch.isSelected() == false) {
                        ch.setSelected(true);
                    }

                }
            }
        }

    }//GEN-LAST:event_tabla_cardexMouseClicked

    void filtro_tabla(String consulta, JTable jtableBuscar) {
        DefaultTableModel dm = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_producto;
    private javax.swing.JDialog Dialog_seguimiento;
    private com.toedter.calendar.JDateChooser datefecha1;
    private com.toedter.calendar.JDateChooser datefecha2;
    private com.toedter.calendar.JDateChooser datefecha3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabla_cardex;
    private javax.swing.JTable tabla_pruducto;
    private javax.swing.JTable tabla_pruducto1;
    private javax.swing.JTextField txt_busqueda_producto;
    private javax.swing.JTextField txt_busqueda_producto1;
    private javax.swing.JTextField txt_descripcion1;
    private javax.swing.JTextField txt_fecha_ven;
    private javax.swing.JTextField txt_id_producto1;
    private javax.swing.JTextField txt_lote;
    // End of variables declaration//GEN-END:variables
}
