/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller_Escritorio;
import Controller.Controller_control_recepcion_producto;
import Entity.Entity_Almacen;
import Entity.Entity_Empresa;
import Entity.Entity_Sucursal;
import Function.Function_Component;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author memo
 */
public class View_Escritorio extends javax.swing.JFrame {

    View_Producto vista_producto;
    View_Ingreso_Productos vista_ingreso_producto;
    View_Salida_producto vista_salida_producto;
    View_Cardex_Fisico cardex_fisico;
    View_Subir_institucion subir_institucion;
    View_Subir_Padron subir_padron;
    View_Usuario usuario;
    View_Empresa empresa;
    View_Punto_operacion punto_opreacion;
    View_Compra compra;
    View_Venta venta;
    View_Cardex_Fisico_X_LOTE cardex_fisico_x_lote;
    View_Stock Stock;
    View_Stock_X_Lote Stock_lote;
    View_Subir_X_Iten subir_iten;
    View_Mostrar_guia guia;
    View_Cardex_Fisico_X_LOTE_Personalizado cardex_per;
    View_Distribuciones distribucion;
    View_Subir_Equipo equipo;
    View_Anexo_9 anexo;
    View_Plan_ruta plan_ruta;
    View_Actas_conformes actas_conforme;
    
    Controller_Escritorio controller_escritorio=new Controller_Escritorio();
    View_Control_recepcion_productos controller_control_recepcion_producto;

    /**
     * Creates new form View_Escritorio
     */
    public View_Escritorio() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        controller_escritorio.cbx_almacen(cbx_almacen);
        controller_escritorio.cbx_empresa(cbx_empresa);
        controller_escritorio.cbx_sucursal(cbx_sucursal);
        
        Function_Component.JComboBox(cbx_almacen);
        Function_Component.JComboBox(cbx_empresa);
        Function_Component.JComboBox(cbx_sucursal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbx_empresa = new javax.swing.JComboBox<>();
        cbx_sucursal = new javax.swing.JComboBox<>();
        cbx_almacen = new javax.swing.JComboBox<>();
        menuBar = new javax.swing.JMenuBar();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem1 = new javax.swing.JMenuItem();
        deleteMenuItem2 = new javax.swing.JMenuItem();
        deleteMenuItem3 = new javax.swing.JMenuItem();
        deleteMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        copyMenuItem1 = new javax.swing.JMenuItem();
        pasteMenuItem1 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        copyMenuItem2 = new javax.swing.JMenuItem();
        copyMenuItem3 = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        fileMenu1 = new javax.swing.JMenu();
        openMenuItem1 = new javax.swing.JMenuItem();
        saveMenuItem1 = new javax.swing.JMenuItem();
        saveAsMenuItem1 = new javax.swing.JMenuItem();
        exitMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jLabel2.setText("id:usuario");
        jToolBar1.add(jLabel2);

        jLabel1.setText("usuario");
        jToolBar1.add(jLabel1);

        jToolBar1.add(cbx_empresa);

        jToolBar1.add(cbx_sucursal);

        jToolBar1.add(cbx_almacen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        editMenu.setMnemonic('e');
        editMenu.setText("ALMACEN");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("PRODUCTO");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("ENTRADA DE MERCADERIA");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("SALIDA DE MERCADERIA");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("CARDEX FISICO");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem);

        deleteMenuItem1.setMnemonic('d');
        deleteMenuItem1.setText("CARDEX FISICO X LOTE");
        deleteMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem1);

        deleteMenuItem2.setMnemonic('d');
        deleteMenuItem2.setText("STOCK PRODUCTO");
        deleteMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItem2ActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem2);

        deleteMenuItem3.setMnemonic('d');
        deleteMenuItem3.setText("STOCK X LOTE");
        deleteMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItem3ActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem3);

        deleteMenuItem4.setMnemonic('d');
        deleteMenuItem4.setText("CARDEX  LOTE");
        deleteMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItem4ActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem4);

        menuBar.add(editMenu);

        jMenu3.setText("MERCADERIA");

        copyMenuItem1.setMnemonic('y');
        copyMenuItem1.setText("COMPRA DE MERCADERIA");
        copyMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(copyMenuItem1);

        pasteMenuItem1.setMnemonic('p');
        pasteMenuItem1.setText("VENTA DE MERCADERIA");
        pasteMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(pasteMenuItem1);

        menuBar.add(jMenu3);

        helpMenu.setMnemonic('h');
        helpMenu.setText("CONFIGURACION MASIVA");

        jMenu1.setText("INSTITUCION ");

        jMenuItem1.setText("SUBIR INSTITUCION");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        helpMenu.add(jMenu1);

        jMenu2.setText("PADRON");

        jMenuItem2.setText("SUBIR PADRON");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        helpMenu.add(jMenu2);

        jMenu5.setText("EQUIPO");

        jMenuItem3.setText("SUBIR EQUIPO");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        helpMenu.add(jMenu5);

        jMenu4.setText("DSITRIBUCION");

        jMenuItem4.setText("CARGAR POR ITEM");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem6.setText("DISTRIBUCION");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("ACTAS CONFORMES");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        helpMenu.add(jMenu4);

        copyMenuItem2.setMnemonic('y');
        copyMenuItem2.setText("ANEXO 9");
        copyMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItem2ActionPerformed(evt);
            }
        });
        helpMenu.add(copyMenuItem2);

        copyMenuItem3.setMnemonic('y');
        copyMenuItem3.setText("PLAN DE RUTA");
        copyMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu.add(copyMenuItem3);

        menuBar.add(helpMenu);

        fileMenu.setMnemonic('f');
        fileMenu.setText("CONFIGURACION");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("USUARIO");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("EMPRESA");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("PUNTO DE OPERACION");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        fileMenu1.setMnemonic('f');
        fileMenu1.setText("BPAL");

        openMenuItem1.setMnemonic('o');
        openMenuItem1.setText("CONTROL DE RECEPCION DE PRODUCTOS");
        openMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu1.add(openMenuItem1);

        saveMenuItem1.setMnemonic('s');
        saveMenuItem1.setText("EMPRESA");
        saveMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu1.add(saveMenuItem1);

        saveAsMenuItem1.setMnemonic('a');
        saveAsMenuItem1.setText("PUNTO DE OPERACION");
        saveAsMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu1.add(saveAsMenuItem1);

        exitMenuItem1.setMnemonic('x');
        exitMenuItem1.setText("Exit");
        exitMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu1.add(exitMenuItem1);

        menuBar.add(fileMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        if (vista_producto == null || vista_producto.isClosed()) {
            vista_producto = new View_Producto();
            vista_producto.setResizable(true);
            desktopPane.add(vista_producto);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = vista_producto.getSize();
            try {
                vista_producto.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vista_producto.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
        if (vista_ingreso_producto == null || vista_ingreso_producto.isClosed()) {
            vista_ingreso_producto = new View_Ingreso_Productos();
            vista_ingreso_producto.setResizable(true);
            desktopPane.add(vista_ingreso_producto);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = vista_ingreso_producto.getSize();
            try {
                vista_ingreso_producto.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vista_ingreso_producto.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
        // TODO add your handling code here:
        if (vista_salida_producto == null || vista_salida_producto.isClosed()) {
            vista_salida_producto = new View_Salida_producto();
            vista_salida_producto.setResizable(true);
            desktopPane.add(vista_salida_producto);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = vista_salida_producto.getSize();
            try {
                vista_salida_producto.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vista_salida_producto.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_pasteMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        // TODO add your handling code here:
        if (cardex_fisico == null || cardex_fisico.isClosed()) {
            cardex_fisico = new View_Cardex_Fisico();
            cardex_fisico.setResizable(true);
            desktopPane.add(cardex_fisico);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = cardex_fisico.getSize();
            try {
                cardex_fisico.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            cardex_fisico.show();
            // vista_usuario.setMaximum(true);
        }


    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:54654
        if (subir_institucion == null || subir_institucion.isClosed()) {
            subir_institucion = new View_Subir_institucion();
            subir_institucion.setResizable(true);
            desktopPane.add(subir_institucion);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = subir_institucion.getSize();
            try {
                subir_institucion.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            subir_institucion.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (subir_padron == null || subir_padron.isClosed()) {
            subir_padron = new View_Subir_Padron();
            subir_padron.setResizable(true);
            desktopPane.add(subir_padron);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = subir_padron.getSize();
            try {
                subir_padron.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            subir_padron.show();
            // vista_usuario.setMaximum(true);
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        if (usuario == null || usuario.isClosed()) {
            usuario = new View_Usuario();
            usuario.setResizable(true);
            desktopPane.add(usuario);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = usuario.getSize();
            try {
                usuario.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            usuario.show();
            // vista_usuario.setMaximum(true);
        }
        
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        if (empresa == null || empresa.isClosed()) {
            empresa = new View_Empresa();
            empresa.setResizable(true);
            desktopPane.add(empresa);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = empresa.getSize();
            try {
                empresa.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            empresa.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:
         if (punto_opreacion == null || punto_opreacion.isClosed()) {
            punto_opreacion = new View_Punto_operacion();
            punto_opreacion.setResizable(true);
            desktopPane.add(punto_opreacion);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = punto_opreacion.getSize();
            try {
                punto_opreacion.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            punto_opreacion.show();
            // vista_usuario.setMaximum(true);
        }
        
        
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void copyMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (compra == null || compra.isClosed()) {
            compra = new View_Compra();
            compra.setResizable(true);
            desktopPane.add(compra);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = compra.getSize();
            try {
                compra.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            compra.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_copyMenuItem1ActionPerformed

    private void pasteMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItem1ActionPerformed
        // TODO add your handling code here:
         if (venta == null || venta.isClosed()) {
            venta = new View_Venta();
            venta.setResizable(true);
            desktopPane.add(venta);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = venta.getSize();
            try {
                venta.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            venta.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_pasteMenuItem1ActionPerformed

    private void deleteMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (cardex_fisico_x_lote == null || cardex_fisico_x_lote.isClosed()) {
            cardex_fisico_x_lote = new View_Cardex_Fisico_X_LOTE();
            cardex_fisico_x_lote.setResizable(true);
            desktopPane.add(cardex_fisico_x_lote);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = cardex_fisico_x_lote.getSize();
            try {
                cardex_fisico_x_lote.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            cardex_fisico_x_lote.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_deleteMenuItem1ActionPerformed

    private void deleteMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (Stock == null || Stock.isClosed()) {
            Stock = new View_Stock();
            Stock.setResizable(true);
            desktopPane.add(Stock);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = Stock.getSize();
            try {
                Stock.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            Stock.show();
            // vista_usuario.setMaximum(true);
        }
        
    }//GEN-LAST:event_deleteMenuItem2ActionPerformed

    private void deleteMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (Stock_lote == null || Stock_lote.isClosed()) {
            Stock_lote = new View_Stock_X_Lote();
            Stock_lote.setResizable(true);
            desktopPane.add(Stock_lote);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = Stock_lote.getSize();
            try {
                Stock_lote.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            Stock_lote.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_deleteMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if (subir_iten == null || subir_iten.isClosed()) {
            subir_iten = new View_Subir_X_Iten();
            subir_iten.setResizable(true);
            desktopPane.add(subir_iten);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = subir_iten.getSize();
            try {
                subir_iten.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            subir_iten.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void deleteMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItem4ActionPerformed
        // TODO add your handling code here:
         if (cardex_per == null || cardex_per.isClosed()) {
            cardex_per = new View_Cardex_Fisico_X_LOTE_Personalizado();
            cardex_per.setResizable(true);
            desktopPane.add(cardex_per);
            Dimension desktopSize = cardex_per.getSize();
            Dimension FrameSize = cardex_per.getSize();
            try {
                cardex_per.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            cardex_per.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_deleteMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
         if (distribucion == null || distribucion.isClosed()) {
            distribucion = new View_Distribuciones();
            distribucion.setResizable(true);
            desktopPane.add(distribucion);
            Dimension desktopSize = distribucion.getSize();
            Dimension FrameSize = distribucion.getSize();
            try {
                distribucion.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            distribucion.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (equipo == null || equipo.isClosed()) {
            equipo = new View_Subir_Equipo();
            equipo.setResizable(true);
            desktopPane.add(equipo);
            Dimension desktopSize = equipo.getSize();
            Dimension FrameSize = equipo.getSize();
            try {
                equipo.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            equipo.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void copyMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (anexo == null || anexo.isClosed()) {
            anexo = new View_Anexo_9();
            anexo.setResizable(true);
            desktopPane.add(anexo);
            Dimension desktopSize = anexo.getSize();
            Dimension FrameSize = anexo.getSize();
            try {
                anexo.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            anexo.show();
            // vista_usuario.setMaximum(true);
        }
        
    }//GEN-LAST:event_copyMenuItem2ActionPerformed

    private void copyMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (plan_ruta == null || plan_ruta.isClosed()) {
            plan_ruta = new View_Plan_ruta();
            plan_ruta.setResizable(true);
            desktopPane.add(plan_ruta);
            Dimension desktopSize = plan_ruta.getSize();
            Dimension FrameSize = plan_ruta.getSize();
            try {
                plan_ruta.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            plan_ruta.show();
            // vista_usuario.setMaximum(true);
        }
    }//GEN-LAST:event_copyMenuItem3ActionPerformed

    private void openMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (controller_control_recepcion_producto == null || controller_control_recepcion_producto.isClosed()) {
            controller_control_recepcion_producto = new View_Control_recepcion_productos();
            controller_control_recepcion_producto.setResizable(true);
            desktopPane.add(controller_control_recepcion_producto);
            Dimension desktopSize = controller_control_recepcion_producto.getSize();
            Dimension FrameSize = controller_control_recepcion_producto.getSize();
            try {
                controller_control_recepcion_producto.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            controller_control_recepcion_producto.show();
            // vista_usuario.setMaximum(true);
        }
        
    }//GEN-LAST:event_openMenuItem1ActionPerformed

    private void saveMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMenuItem1ActionPerformed

    private void saveAsMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveAsMenuItem1ActionPerformed

    private void exitMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        if (actas_conforme == null || actas_conforme.isClosed()) {
            actas_conforme = new View_Actas_conformes();
            actas_conforme.setResizable(true);
            desktopPane.add(actas_conforme);
            Dimension desktopSize = actas_conforme.getSize();
            Dimension FrameSize = actas_conforme.getSize();
            try {
                actas_conforme.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(View_Escritorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            // vista_producto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            actas_conforme.show();
            // vista_usuario.setMaximum(true);
        }
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<Entity_Almacen> cbx_almacen;
    public static javax.swing.JComboBox<Entity_Empresa> cbx_empresa;
    public static javax.swing.JComboBox<Entity_Sucursal> cbx_sucursal;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem copyMenuItem1;
    private javax.swing.JMenuItem copyMenuItem2;
    private javax.swing.JMenuItem copyMenuItem3;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem deleteMenuItem1;
    private javax.swing.JMenuItem deleteMenuItem2;
    private javax.swing.JMenuItem deleteMenuItem3;
    private javax.swing.JMenuItem deleteMenuItem4;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exitMenuItem1;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu fileMenu1;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem openMenuItem1;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem pasteMenuItem1;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem1;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem saveMenuItem1;
    // End of variables declaration//GEN-END:variables

}
