/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller_Empresa;
import Controller.Controller_Punto_operacion;
import Entity.Entity_Punto_operacion;
import Entity.Entity_Sucursal;
import Function.Function_Component;
import Function.Function_Key_Event;
import Function.Function_ShowMessageDialog;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pro
 */
public class View_Punto_operacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form View_Punto_operacion
     */
    Controller_Punto_operacion punto_operacion = new Controller_Punto_operacion();
    Entity_Punto_operacion entity_punto_operacion;

    public View_Punto_operacion() {
        initComponents();
        punto_operacion.punto_operacion(tabla_punto_operacion, Dialog_tipo_documento, tabla_tipo_documento, TITLE_PROPERTY);
        txt_id_sucursal.setVisible(false);
        txt_id_punto_operacion.setVisible(false);
        deshabilitar();
        Function_Key_Event.Validar_Mayuscula(txtcod_punto_operacion);
        Function_Component.JTextField(txt_ruc);
        Function_Component.JTextField(txt_razon_social);
        Function_Component.JTextField(txt_razon_comercial);
        Function_Component.JCheckBox(check_estado);
        
        
        Function_Component.JButton(btn_busacr);
        Function_Component.JButton(btn_editar);
        Function_Component.JButton(btn_busacr1);
        Function_Component.JButton(btn_argegar_fila);
        Function_Component.JButton(btn_argegar_fila_usuario);
        Function_Component.JButton(btn_guardar);
        Function_Component.JButton(btn_cancelar);
        Function_Component.JTabbedPane(jTabbedPane1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_sucursal = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_sucursal = new javax.swing.JTable();
        Dialog_tipo_documento = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_tipo_documento = new javax.swing.JTable();
        Dialog_punto_operacion = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_punto_ope = new javax.swing.JTable();
        Dialog_usuario = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabla_user = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtcod_punto_operacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_id_punto_operacion = new javax.swing.JTextField();
        btn_busacr = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_punto_operacion = new javax.swing.JTable();
        btn_argegar_fila = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_usaurio = new javax.swing.JTable();
        btn_argegar_fila_usuario = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txt_ruc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_razon_social = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_razon_comercial = new javax.swing.JTextField();
        btn_busacr1 = new javax.swing.JButton();
        txt_id_sucursal = new javax.swing.JTextField();
        check_estado = new javax.swing.JCheckBox();

        Dialog_sucursal.setTitle("EMPRESA-SUCURSAL");
        Dialog_sucursal.setLocationByPlatform(true);
        Dialog_sucursal.setMinimumSize(new java.awt.Dimension(610, 385));
        Dialog_sucursal.setModal(true);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        tabla_sucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_sucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_sucursalMouseClicked(evt);
            }
        });
        tabla_sucursal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_sucursalKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tabla_sucursal);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Dialog_sucursalLayout = new javax.swing.GroupLayout(Dialog_sucursal.getContentPane());
        Dialog_sucursal.getContentPane().setLayout(Dialog_sucursalLayout);
        Dialog_sucursalLayout.setHorizontalGroup(
            Dialog_sucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Dialog_sucursalLayout.setVerticalGroup(
            Dialog_sucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_sucursalLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        Dialog_tipo_documento.setTitle("TIPO DOCUMENTO");
        Dialog_tipo_documento.setAutoRequestFocus(false);
        Dialog_tipo_documento.setMinimumSize(new java.awt.Dimension(619, 344));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        tabla_tipo_documento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_tipo_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_tipo_documentoMouseClicked(evt);
            }
        });
        tabla_tipo_documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_tipo_documentoKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tabla_tipo_documento);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout Dialog_tipo_documentoLayout = new javax.swing.GroupLayout(Dialog_tipo_documento.getContentPane());
        Dialog_tipo_documento.getContentPane().setLayout(Dialog_tipo_documentoLayout);
        Dialog_tipo_documentoLayout.setHorizontalGroup(
            Dialog_tipo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_tipo_documentoLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        Dialog_tipo_documentoLayout.setVerticalGroup(
            Dialog_tipo_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_tipo_documentoLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        Dialog_punto_operacion.setTitle("PUNTO DE OPERACION");
        Dialog_punto_operacion.setLocationByPlatform(true);
        Dialog_punto_operacion.setMinimumSize(new java.awt.Dimension(610, 385));
        Dialog_punto_operacion.setModal(true);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        tabla_punto_ope.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_punto_ope.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_punto_opeMouseClicked(evt);
            }
        });
        tabla_punto_ope.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_punto_opeKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(tabla_punto_ope);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Dialog_punto_operacionLayout = new javax.swing.GroupLayout(Dialog_punto_operacion.getContentPane());
        Dialog_punto_operacion.getContentPane().setLayout(Dialog_punto_operacionLayout);
        Dialog_punto_operacionLayout.setHorizontalGroup(
            Dialog_punto_operacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Dialog_punto_operacionLayout.setVerticalGroup(
            Dialog_punto_operacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_punto_operacionLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        Dialog_usuario.setTitle("TIPO USUARIO");
        Dialog_usuario.setAutoRequestFocus(false);
        Dialog_usuario.setMinimumSize(new java.awt.Dimension(619, 344));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        tabla_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_userMouseClicked(evt);
            }
        });
        tabla_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_userKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(tabla_user);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout Dialog_usuarioLayout = new javax.swing.GroupLayout(Dialog_usuario.getContentPane());
        Dialog_usuario.getContentPane().setLayout(Dialog_usuarioLayout);
        Dialog_usuarioLayout.setHorizontalGroup(
            Dialog_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_usuarioLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        Dialog_usuarioLayout.setVerticalGroup(
            Dialog_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_usuarioLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("PUNTO DE OPERACION");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtcod_punto_operacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcod_punto_operacionKeyPressed(evt);
            }
        });

        jLabel1.setText("Codigo ponto de operacion");

        btn_busacr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_busqueda1.png"))); // NOI18N
        btn_busacr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busacrActionPerformed(evt);
            }
        });

        btn_editar.setText("EDITAR COD");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtcod_punto_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id_punto_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_busacr, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_busacr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_id_punto_operacion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcod_punto_operacion)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tabla_punto_operacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_punto_operacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_punto_operacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_punto_operacion);

        btn_argegar_fila.setText("+");
        btn_argegar_fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_argegar_filaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(btn_argegar_fila)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btn_argegar_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PUNTO DE OPERACION", jPanel5);

        tabla_usaurio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_usaurio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_usaurioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_usaurio);

        btn_argegar_fila_usuario.setText("+");
        btn_argegar_fila_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_argegar_fila_usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_argegar_fila_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btn_argegar_fila_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("USUARIOS", jPanel6);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de empresa"));

        txt_ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_rucKeyPressed(evt);
            }
        });

        jLabel2.setText("RUC:");

        jLabel3.setText("RAZON SOCIAL");

        txt_razon_social.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_razon_socialKeyPressed(evt);
            }
        });

        jLabel4.setText("CODIGO SUCURSAL");

        txt_razon_comercial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_razon_comercialKeyPressed(evt);
            }
        });

        btn_busacr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_busqueda1.png"))); // NOI18N
        btn_busacr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busacr1ActionPerformed(evt);
            }
        });

        txt_id_sucursal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_id_sucursalKeyPressed(evt);
            }
        });

        check_estado.setSelected(true);
        check_estado.setText("ACTIVO");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(check_estado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_razon_comercial, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_razon_social, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .addComponent(txt_ruc, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_busacr1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_id_sucursal)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ruc))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_busacr1))
                    .addComponent(txt_id_sucursal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_razon_social)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_razon_comercial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_estado)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcod_punto_operacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcod_punto_operacionKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String id_punto_op = punto_operacion.Id_Punto_operacion(txtcod_punto_operacion.getText());
            if (id_punto_op.equals("0")) {
                
                limpiar();
                cargar_usuario(txtcod_punto_operacion.getText());
                punto_operacion.punto_operacion(tabla_punto_operacion, Dialog_tipo_documento, tabla_tipo_documento, txt_id_punto_operacion.getText());
                punto_operacion.punto_operacion_usuario(tabla_usaurio, Dialog_usuario, tabla_user,txt_id_punto_operacion.getText());
                habilitar();
                btn_guardar.setEnabled(true);
                //btn_eliminar.setEnabled(true);
                /*btn_cancelar.setEnabled(true);*/
                btn_editar.setEnabled(true);

            } else if (id_punto_op.equals("fallo")) {

            } else {
                punto_operacion.punto_operacion(tabla_punto_operacion, Dialog_tipo_documento, tabla_tipo_documento, TITLE_PROPERTY);
                punto_operacion.punto_operacion_usuario(tabla_usaurio, Dialog_usuario, tabla_user,TITLE_PROPERTY);

                limpiar();
                habilitar();
                txt_id_punto_operacion.setText(id_punto_op);
                btn_guardar.setEnabled(true);
                //btn_eliminar.setEnabled(true);
                //btn_cancelar.setEnabled(true);
                btn_editar.setEnabled(false);

            }
            //
            //txt_ruc.requestFocus();
            txtcod_punto_operacion.setEnabled(false);
            txt_ruc.requestFocus();
            evt.consume();
        }
        
    }//GEN-LAST:event_txtcod_punto_operacionKeyPressed

    private void btn_busacrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busacrActionPerformed
        // TODO add your handling code here:
        punto_operacion.table_punta_operacion(tabla_punto_ope);
        Dimension desktopSize = jPanel1.getSize();
        Dimension FrameSize = Dialog_punto_operacion.getSize();
        Dialog_punto_operacion.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Dialog_punto_operacion.setVisible(true);
    }//GEN-LAST:event_btn_busacrActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        /*try {
            String respuesta = JOptionPane.showInputDialog("Escribe nuevo codigo:");
            if (respuesta.length() > 0) {
                String resultado = new Controller_Empresa().Edit_cod_empresa(respuesta, txtid_empresa.getText());
                txtcod_empresa.setText(respuesta);
            }

        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_btn_editarActionPerformed

    private void txt_razon_comercialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_razon_comercialKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_razon_comercialKeyPressed

    private void txt_razon_socialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_razon_socialKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_razon_socialKeyPressed

    private void txt_rucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rucKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_rucKeyPressed

    private void btn_busacr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busacr1ActionPerformed
        // TODO add your handling code here:
        punto_operacion.table_sucursal(tabla_sucursal);
        Dimension desktopSize = jPanel1.getSize();
        Dimension FrameSize = Dialog_sucursal.getSize();
        Dialog_sucursal.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Dialog_sucursal.setVisible(true);
    }//GEN-LAST:event_btn_busacr1ActionPerformed

    private void tabla_sucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_sucursalMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tabla_sucursalMouseClicked

    private void tabla_sucursalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_sucursalKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_ruc.setText(tabla_sucursal.getValueAt(tabla_sucursal.getSelectedRow(), 0).toString());
            txt_razon_social.setText(tabla_sucursal.getValueAt(tabla_sucursal.getSelectedRow(), 1).toString());
            txt_id_sucursal.setText(tabla_sucursal.getValueAt(tabla_sucursal.getSelectedRow(), 2).toString());
            txt_razon_comercial.setText(tabla_sucursal.getValueAt(tabla_sucursal.getSelectedRow(), 3).toString());
            Dialog_sucursal.dispose();
            evt.consume();
        }
    }//GEN-LAST:event_tabla_sucursalKeyPressed

    private void txt_id_sucursalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_sucursalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_sucursalKeyPressed

    private void tabla_tipo_documentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_tipo_documentoMouseClicked
        // TODO add your handling code here:
        tabla_punto_operacion.setValueAt(tabla_tipo_documento.getValueAt(tabla_tipo_documento.getSelectedRow(), 0), tabla_punto_operacion.getSelectedRow() + punto_operacion.variable(), 3);
        tabla_punto_operacion.setValueAt(tabla_tipo_documento.getValueAt(tabla_tipo_documento.getSelectedRow(), 2), tabla_punto_operacion.getSelectedRow() + punto_operacion.variable(), 4);
    }//GEN-LAST:event_tabla_tipo_documentoMouseClicked

    private void tabla_punto_operacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_punto_operacionMouseClicked
        // TODO add your handling code here:
        punto_operacion.reset_variable();
        int fila = tabla_punto_operacion.rowAtPoint(evt.getPoint());
        int column = tabla_punto_operacion.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tabla_punto_operacion.getRowHeight();
        if (row < tabla_punto_operacion.getRowCount() && row >= 0 && column < tabla_punto_operacion.getColumnCount() && column >= 0) {
            Object value = tabla_punto_operacion.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btneliminar")) {

                    if (tabla_punto_operacion.getSelectedRow() != -1) {
                        /*DefaultTableModel model = (DefaultTableModel) tabla_productos_presentacion.getModel();
                        model.removeRow(tabla_productos_presentacion.getSelectedRow());*/
                        if (tabla_punto_operacion.getValueAt(fila, 1).toString().equals("")) {
                            DefaultTableModel model = (DefaultTableModel) tabla_punto_operacion.getModel();
                            model.removeRow(tabla_punto_operacion.getSelectedRow());
                        } else if (tabla_punto_operacion.getValueAt(fila, 1).toString().equals(null)) {
                            System.out.println("1");
                        } else {
                            if (punto_operacion.delete_punto_operacion(tabla_punto_operacion.getValueAt(tabla_punto_operacion.getSelectedRow(), 1).toString()).equals("exito")) {
                                DefaultTableModel model = (DefaultTableModel) tabla_punto_operacion.getModel();
                                model.removeRow(tabla_punto_operacion.getSelectedRow());
                            }else{
                                JOptionPane.showMessageDialog(rootPane,"ERROR NO PUEDO ELIMINARSE");
                        
                            }
;
                            
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "sss");
                    }

                }

            }
            if (value instanceof JCheckBox) {
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox) value;
                if (ch.isSelected() == true) {
                    ch.setSelected(false);
                }
                if (ch.isSelected() == false) {
                    ch.setSelected(true);
                }

            }
        }
    }//GEN-LAST:event_tabla_punto_operacionMouseClicked

    private void tabla_tipo_documentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_tipo_documentoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tabla_punto_operacion.setValueAt(tabla_tipo_documento.getValueAt(tabla_tipo_documento.getSelectedRow(), 0), tabla_punto_operacion.getSelectedRow() + punto_operacion.variable(), 3);
            tabla_punto_operacion.setValueAt(tabla_tipo_documento.getValueAt(tabla_tipo_documento.getSelectedRow(), 2), tabla_punto_operacion.getSelectedRow() + punto_operacion.variable(), 4);
            Dialog_tipo_documento.dispose();
            evt.consume();
        }

    }//GEN-LAST:event_tabla_tipo_documentoKeyPressed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
         if (txt_id_sucursal.getText().length() == 0) {
            Function_ShowMessageDialog.ShowMessageDialogvalidacion(rootPane, "CAMPO VACIO");
            return;
        }
        
        int tabla = 0;
        tabla_punto_operacion.editCellAt(0, 4);
        Component aComp = tabla_punto_operacion.getEditorComponent();
        aComp.requestFocus();
        for (int j = 0; j < tabla_punto_operacion.getRowCount(); j++) {
            try {

                for (int i = 3; i < tabla_punto_operacion.getColumnCount() - 3; i++) {
                    if (tabla_punto_operacion.getValueAt(j, i).toString() == ("")) {
                        JOptionPane.showMessageDialog(rootPane, "HAY CAMPO VACIO:" + tabla_punto_operacion.getTableHeader().getColumnModel().getColumn(i).getHeaderValue());
                        tabla = tabla + 1;
                        tabla_punto_operacion.editCellAt(j, i);
                        Component aComp1 = tabla_punto_operacion.getEditorComponent();
                        aComp1.requestFocus();
                        break;

                    } else if (tabla_punto_operacion.getValueAt(j, i).toString().length() == 0) {
                        JOptionPane.showMessageDialog(rootPane, "HAY CAMPO VACIO:" + tabla_punto_operacion.getTableHeader().getColumnModel().getColumn(i).getHeaderValue());
                        tabla = tabla + 1;
                        tabla_punto_operacion.editCellAt(j, i);
                        Component aComp1 = tabla_punto_operacion.getEditorComponent();
                        aComp1.requestFocus();
                        break;

                    }

                }
                if (tabla > 0) {
                    break;

                }
            } catch (Exception e) {
            }
        }

        if (tabla > 0) {
            return;

        }
        
        
        for (int j = 0; j < tabla_usaurio.getRowCount(); j++) {
            try {

                for (int i = 2; i < tabla_usaurio.getColumnCount() - 2; i++) {
                    if (tabla_usaurio.getValueAt(j, i).toString() == ("")) {
                        JOptionPane.showMessageDialog(rootPane, "HAY CAMPO VACIO:" + tabla_usaurio.getTableHeader().getColumnModel().getColumn(i).getHeaderValue());
                        tabla = tabla + 1;
                        tabla_usaurio.editCellAt(j, i);
                        Component aComp1 = tabla_usaurio.getEditorComponent();
                        aComp1.requestFocus();
                        break;

                    } else if (tabla_usaurio.getValueAt(j, i).toString().length() == 0) {
                        JOptionPane.showMessageDialog(rootPane, "HAY CAMPO VACIO:" + tabla_usaurio.getTableHeader().getColumnModel().getColumn(i).getHeaderValue());
                        tabla = tabla + 1;
                        tabla_usaurio.editCellAt(j, i);
                        Component aComp1 = tabla_usaurio.getEditorComponent();
                        aComp1.requestFocus();
                        break;

                    }

                }
                if (tabla > 0) {
                    break;

                }
            } catch (Exception e) {
            }
        }

        if (tabla > 0) {
            return;

        }
        
        
        entity_punto_operacion = new Entity_Punto_operacion(txt_id_punto_operacion.getText(), txtcod_punto_operacion.getText(), txt_id_sucursal.getText(), check_estado.isSelected());
        
        if (punto_operacion.Add_Punto_operacion(entity_punto_operacion).equals("exito")) {
            
            
            for (int i = 0; i < tabla_punto_operacion.getRowCount(); i++) {
                entity_punto_operacion = new Entity_Punto_operacion(
                        tabla_punto_operacion.getValueAt(i, 1).toString(), txt_id_punto_operacion.getText(),
                        tabla_punto_operacion.getValueAt(i, 3).toString(), tabla_punto_operacion.getValueAt(i, 5).toString(),
                        tabla_punto_operacion.getValueAt(i, 6).toString(), tabla_punto_operacion.getValueAt(i, 7).toString(),
                        tabla_punto_operacion.getValueAt(i, 8).toString(), tabla_punto_operacion.getValueAt(i, 9).toString(),
                        tabla_punto_operacion.getValueAt(i, 10).toString()
                        );
                punto_operacion.Add_detalle_punto_operacion(entity_punto_operacion);
              /*  /*String respuesta_sucursal= /punto_operacion()*/
            }
            for (int i = 0; i < tabla_usaurio.getRowCount(); i++) {
                entity_punto_operacion = new Entity_Punto_operacion(
                        tabla_usaurio.getValueAt(i, 1).toString(), txt_id_punto_operacion.getText(),
                        tabla_usaurio.getValueAt(i, 2).toString(), tabla_usaurio.getValueAt(i, 5).toString()
                        );
                punto_operacion.Add_detalle_punto_operacion_usuario(entity_punto_operacion);
              /*  /*String respuesta_sucursal= /punto_operacion()*/
            }
            
        }
        punto_operacion.punto_operacion(tabla_punto_operacion, Dialog_tipo_documento, tabla_tipo_documento, TITLE_PROPERTY);
        punto_operacion.punto_operacion_usuario(tabla_usaurio, Dialog_usuario, tabla_user, TITLE_PROPERTY);
        limpiar();
        deshabilitar();
        txtcod_punto_operacion.setEnabled(true);
        txtcod_punto_operacion.requestFocus();
        txtcod_punto_operacion.setText("");
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        punto_operacion.punto_operacion(tabla_punto_operacion, Dialog_tipo_documento, tabla_tipo_documento, TITLE_PROPERTY);
        punto_operacion.punto_operacion_usuario(tabla_usaurio, Dialog_usuario, tabla_user, TITLE_PROPERTY);
        limpiar();
        deshabilitar();
        txtcod_punto_operacion.setEnabled(true);
        txtcod_punto_operacion.requestFocus();
        txtcod_punto_operacion.setText("");
        
        
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void tabla_punto_opeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_punto_opeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_punto_opeMouseClicked

    private void tabla_punto_opeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_punto_opeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

           
                
                limpiar();
                cargar_usuario(tabla_punto_ope.getValueAt(tabla_punto_ope.getSelectedRow(), 1).toString());
                punto_operacion.punto_operacion(tabla_punto_operacion, Dialog_tipo_documento, tabla_tipo_documento, txt_id_punto_operacion.getText());
                punto_operacion.punto_operacion_usuario(tabla_usaurio, Dialog_usuario, tabla_user,txt_id_punto_operacion.getText());
                habilitar();
                btn_guardar.setEnabled(true);
                //btn_eliminar.setEnabled(true);
                /*btn_cancelar.setEnabled(true);*/
                btn_editar.setEnabled(true);

            

            //
            //txt_ruc.requestFocus();
            txtcod_punto_operacion.setEnabled(false);
            txt_ruc.requestFocus();
            Dialog_punto_operacion.dispose();
            evt.consume();
        }
    }//GEN-LAST:event_tabla_punto_opeKeyPressed

    private void btn_argegar_filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_argegar_filaActionPerformed
        // TODO add your handling code here:
        punto_operacion.add_punto_operacion(tabla_punto_operacion, Dialog_tipo_documento, tabla_tipo_documento);
    }//GEN-LAST:event_btn_argegar_filaActionPerformed

    private void tabla_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_userMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_userMouseClicked

    private void tabla_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_userKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tabla_usaurio.setValueAt(tabla_user.getValueAt(tabla_user.getSelectedRow(), 0), tabla_usaurio.getSelectedRow() + punto_operacion.variable_usuario(), 2);
            tabla_usaurio.setValueAt(tabla_user.getValueAt(tabla_user.getSelectedRow(), 2), tabla_usaurio.getSelectedRow() + punto_operacion.variable_usuario(), 3);
            Dialog_usuario.dispose();
            evt.consume();
        }
        
    }//GEN-LAST:event_tabla_userKeyPressed

    private void tabla_usaurioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_usaurioMouseClicked
        // TODO add your handling code here:
        punto_operacion.reset_variable_usuario();
        int fila = tabla_usaurio.rowAtPoint(evt.getPoint());
        int column = tabla_usaurio.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tabla_usaurio.getRowHeight();
        if (row < tabla_usaurio.getRowCount() && row >= 0 && column < tabla_usaurio.getColumnCount() && column >= 0) {
            Object value = tabla_usaurio.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btneliminar")) {

                    if (tabla_usaurio.getSelectedRow() != -1) {
                        /*DefaultTableModel model = (DefaultTableModel) tabla_productos_presentacion.getModel();
                        model.removeRow(tabla_productos_presentacion.getSelectedRow());*/
                        if (tabla_usaurio.getValueAt(fila, 1).toString().equals("")) {
                            DefaultTableModel model = (DefaultTableModel) tabla_usaurio.getModel();
                            model.removeRow(tabla_usaurio.getSelectedRow());
                        } else if (tabla_usaurio.getValueAt(fila, 1).toString().equals(null)) {
                            System.out.println("1");
                        } else {
                            //String respuesta=new Controller_Empresa().delete_sucursal(tabla_punto_operacion.getValueAt(tabla_punto_operacion.getSelectedRow(), 1).toString());
                           
                            if (punto_operacion.delete_punto_operacion_usuario(tabla_usaurio.getValueAt(tabla_usaurio.getSelectedRow(), 1).toString()).equals("exito")) {
                                DefaultTableModel model = (DefaultTableModel) tabla_usaurio.getModel();
                                model.removeRow(tabla_usaurio.getSelectedRow());
                            }else{
                                JOptionPane.showMessageDialog(rootPane,"ERROR NO PUEDO ELIMINARSE");
                        
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "sss");
                    }

                }

            }
            if (value instanceof JCheckBox) {
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox) value;
                if (ch.isSelected() == true) {
                    ch.setSelected(false);
                }
                if (ch.isSelected() == false) {
                    ch.setSelected(true);
                }

            }
        }
    }//GEN-LAST:event_tabla_usaurioMouseClicked

    private void btn_argegar_fila_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_argegar_fila_usuarioActionPerformed
        // TODO add your handling code here:
        punto_operacion.add_punto_operacion_usuario(tabla_usaurio, Dialog_usuario, tabla_user);
    }//GEN-LAST:event_btn_argegar_fila_usuarioActionPerformed
    void cargar_usuario(String cod_usuario) {
        List<Entity_Punto_operacion> punto_operacion = new Controller_Punto_operacion().buscar_punto_operacion(cod_usuario);
        txt_id_punto_operacion.setText(punto_operacion.get(0).getPunto_op_id());
        txtcod_punto_operacion.setText(punto_operacion.get(0).getPunto_op_cod());
        txt_id_sucursal.setText(punto_operacion.get(0).getPunto_op_sucursal());
        check_estado.setSelected(punto_operacion.get(0).getPunto_op_estado());
        txt_ruc.setText(punto_operacion.get(0).getEmpresa_ruc());
        txt_razon_social.setText(punto_operacion.get(0).getEmpresa_razon_social());
        txt_razon_comercial.setText(punto_operacion.get(0).getSucursal_cod());
    }
    void limpiar(){
        txt_id_punto_operacion.setText("");
        //txtcod_punto_operacion.setText("");
        txt_id_sucursal.setText("");
        check_estado.setText("");
        txt_ruc.setText("");
        txt_razon_social.setText("");
        txt_razon_comercial.setText("");
        
        
    }
    void habilitar(){
        
        txt_ruc.setEnabled(true);
        btn_busacr1.setEnabled(true);
        txt_razon_social.setEnabled(false);
        txt_razon_comercial.setEnabled(false);
        check_estado.setEnabled(true);
        btn_guardar.setEnabled(true);
        btn_cancelar.setEnabled(true);
    
    }
    void deshabilitar(){
        txt_ruc.setEnabled(false);
        btn_busacr1.setEnabled(false);
        txt_razon_social.setEnabled(false);
        txt_razon_comercial.setEnabled(false);
        check_estado.setEnabled(false);
        btn_guardar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_punto_operacion;
    private javax.swing.JDialog Dialog_sucursal;
    private javax.swing.JDialog Dialog_tipo_documento;
    private javax.swing.JDialog Dialog_usuario;
    public static javax.swing.JButton btn_argegar_fila;
    public static javax.swing.JButton btn_argegar_fila_usuario;
    private javax.swing.JButton btn_busacr;
    private javax.swing.JButton btn_busacr1;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JCheckBox check_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabla_punto_ope;
    private javax.swing.JTable tabla_punto_operacion;
    private javax.swing.JTable tabla_sucursal;
    private javax.swing.JTable tabla_tipo_documento;
    private javax.swing.JTable tabla_usaurio;
    private javax.swing.JTable tabla_user;
    private javax.swing.JTextField txt_id_punto_operacion;
    private javax.swing.JTextField txt_id_sucursal;
    private javax.swing.JTextField txt_razon_comercial;
    private javax.swing.JTextField txt_razon_social;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txtcod_punto_operacion;
    // End of variables declaration//GEN-END:variables
}
