/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Conexion.Conexion;
import Controller.Controller_Empresa;
import Controller.Controller_Usuario;
import Entity.Entity_Compra_Producto;
import Entity.Entity_Empresa;
import Entity.Entity_Sucursal;
import Entity.Entity_Usuario;
import Function.Function_ShowMessageDialog;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pro
 */
public class View_Empresa extends javax.swing.JInternalFrame {

    Entity_Empresa empresa;
    Entity_Sucursal sucursal;
    Controller_Empresa controller_empresa=new Controller_Empresa();
    

    /**
     * Creates new form View_Empresa
     */
    public View_Empresa() {
        initComponents();
        deshabilitar();
        txtid_empresa.setVisible(false);
        Function.Function_Key_Event.Validar_Mayuscula(txtcod_empresa);
        Function.Function_Key_Event.Validar_numeros(txt_ruc);
        Function.Function_Key_Event.Validar_Mayuscula(txt_razon_social);
        Function.Function_Key_Event.Validar_Mayuscula(txt_razon_comercial);
        Function.Function_Key_Event.Validar_Mayuscula(txt_direccion);
        Function.Function_Key_Event.Validar_Mayuscula(txt_Descrip);
        Function.Function_Component.JButton(btn_guardar_imagen);
        Function.Function_Component.JButton(btn_busacr);
        Function.Function_Component.JButton(btn_editar);
        Function.Function_Component.JButton(btn_guardar);
        Function.Function_Component.JButton(btn_agregar_fila);
        Function.Function_Component.JButton(btn_cancelar);
        controller_empresa.empresa(tabla_sucursal,TITLE_PROPERTY);
        controller_empresa.Almacen(tabla_almacen, title);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_empresa = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_empresa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtcod_empresa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtid_empresa = new javax.swing.JTextField();
        btn_busacr = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txt_ruc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_razon_social = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_razon_comercial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        txt_Descrip = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_imagen = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_url = new javax.swing.JTextField();
        btn_guardar_imagen = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        box_estado = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_sucursal = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btn_agregar_fila = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_almacen = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        btn_agregar_fila_almacen = new javax.swing.JButton();

        Dialog_empresa.setMinimumSize(new java.awt.Dimension(610, 350));
        Dialog_empresa.setModal(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tabla_empresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_empresaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_empresa);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Dialog_empresaLayout = new javax.swing.GroupLayout(Dialog_empresa.getContentPane());
        Dialog_empresa.getContentPane().setLayout(Dialog_empresaLayout);
        Dialog_empresaLayout.setHorizontalGroup(
            Dialog_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_empresaLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        Dialog_empresaLayout.setVerticalGroup(
            Dialog_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("EMPRESA");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtcod_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcod_empresaKeyPressed(evt);
            }
        });

        jLabel1.setText("Codigo empresa");

        btn_busacr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_busqueda1.png"))); // NOI18N
        btn_busacr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busacrActionPerformed(evt);
            }
        });

        btn_editar.setText("EDITAR COD");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(647, 647, 647))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtcod_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_busacr, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_busacr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcod_empresa)
                    .addComponent(txtid_empresa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de empresa"));

        txt_ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_rucKeyPressed(evt);
            }
        });

        jLabel2.setText("RUC:");

        jLabel3.setText("RAZON SOCIAL");

        txt_razon_social.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_razon_socialKeyPressed(evt);
            }
        });

        jLabel4.setText("RAZON COMERCIAL:");

        txt_razon_comercial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_razon_comercialKeyPressed(evt);
            }
        });

        jLabel5.setText("RAZON DIRECCION");

        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_direccionKeyPressed(evt);
            }
        });

        txt_Descrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_DescripKeyPressed(evt);
            }
        });

        jLabel6.setText("DESCRIPCION ADICIONAL");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen"));

        jLabel8.setText("DESCRIPCION ADICIONAL");

        btn_guardar_imagen.setText("SUBIR IMAGEN");
        btn_guardar_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_imagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_url)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_guardar_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_guardar_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_url))
                .addGap(11, 11, 11))
        );

        jLabel9.setText("Estado");

        box_estado.setSelected(true);
        box_estado.setText("Activo");
        box_estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                box_estadoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Descrip, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_razon_comercial, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_razon_social, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(txt_ruc, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(box_estado))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ruc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_razon_social)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_razon_comercial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_direccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Descrip)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box_estado)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tabla_sucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_sucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_sucursalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_sucursal);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btn_agregar_fila.setText("+");
        btn_agregar_fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_filaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btn_agregar_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btn_agregar_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("SUCURSALES", jPanel4);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        tabla_almacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_almacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_almacenMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabla_almacen);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        btn_agregar_fila_almacen.setText("+");
        btn_agregar_fila_almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_fila_almacenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btn_agregar_fila_almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btn_agregar_fila_almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("ALMACEN", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardar_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_imagenActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser();
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("JPG, PNG  ", "jpg", "png");
        archivo.setFileFilter(filtroImagen);
        int ventana = archivo.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION) {
            File file = archivo.getSelectedFile();
            txt_url.setText("" + file);
            Image foto = getToolkit().getImage(txt_url.getText());
            foto = foto.getScaledInstance(lbl_imagen.getWidth(), lbl_imagen.getHeight(), Image.SCALE_DEFAULT);
            lbl_imagen.setIcon(new ImageIcon(foto));
        }
        
    }//GEN-LAST:event_btn_guardar_imagenActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        controller_empresa.empresa(tabla_sucursal,TITLE_PROPERTY);
        controller_empresa.Almacen(tabla_almacen,TITLE_PROPERTY);
        limpiar();
        deshabilitar();
        txtcod_empresa.setText("");
        txtid_empresa.setText("");
        txtcod_empresa.setEnabled(true);
        txtcod_empresa.requestFocus();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void box_estadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_box_estadoKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER)) {
            //  btn_agregar_fila.requestFocus();
        }
    }//GEN-LAST:event_box_estadoKeyPressed

    private void btn_busacrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busacrActionPerformed
        // TODO add your handling code here:
        new Controller_Empresa().table_empresa(tabla_empresa);
        Dimension desktopSize = jPanel1.getSize();
        Dimension FrameSize = Dialog_empresa.getSize();
        Dialog_empresa.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Dialog_empresa.setVisible(true);
    }//GEN-LAST:event_btn_busacrActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        try {
            String respuesta = JOptionPane.showInputDialog("Escribe nuevo codigo:");
            if (respuesta.length() > 0) {
                String resultado = new Controller_Empresa().Edit_cod_empresa(respuesta, txtid_empresa.getText());
                txtcod_empresa.setText(respuesta);
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        if (txtid_empresa.getText().length() == 0) {
            Function_ShowMessageDialog.ShowMessageDialogvalidacion(rootPane, "CAMPO VACIO");
            return;
        }
        if (txtcod_empresa.getText().length() == 0) {
            Function_ShowMessageDialog.ShowMessageDialogvalidacion(rootPane, "CAMPO VACIO");
            return;
        }
        if (txt_ruc.getText().length() == 0) {
            Function_ShowMessageDialog.ShowMessageDialogvalidacion(rootPane, "CAMPO VACIO");
            return;
        }
        if (txt_razon_social.getText().length() == 0) {
            Function_ShowMessageDialog.ShowMessageDialogvalidacion(rootPane, "CAMPO VACIO");
            return;
        }
        if (txt_razon_comercial.getText().length() == 0) {
            Function_ShowMessageDialog.ShowMessageDialogvalidacion(rootPane, "CAMPO VACIO");
            return;
        }
        if (txt_direccion.getText().length() == 0) {
            Function_ShowMessageDialog.ShowMessageDialogvalidacion(rootPane, "CAMPO VACIO");
            return;
        }
        
        int tabla = 0;
        tabla_sucursal.editCellAt(0, 3);
        Component aComp = tabla_sucursal.getEditorComponent();
        aComp.requestFocus();
        for (int j = 0; j < tabla_sucursal.getRowCount(); j++) {
            try {

                for (int i = 3; i < tabla_sucursal.getColumnCount() - 3; i++) {
                    if (tabla_sucursal.getValueAt(j, i).toString() == ("")) {
                        JOptionPane.showMessageDialog(rootPane, "HAY CAMPO VACIO:" + tabla_sucursal.getTableHeader().getColumnModel().getColumn(i).getHeaderValue());
                        tabla = tabla + 1;
                        tabla_sucursal.editCellAt(j, i);
                        Component aComp1 = tabla_sucursal.getEditorComponent();
                        aComp1.requestFocus();
                        break;

                    } else if (tabla_sucursal.getValueAt(j, i).toString().length() == 0) {
                        JOptionPane.showMessageDialog(rootPane, "HAY CAMPO VACIO:" + tabla_sucursal.getTableHeader().getColumnModel().getColumn(i).getHeaderValue());
                        tabla = tabla + 1;
                        tabla_sucursal.editCellAt(j, i);
                        Component aComp1 = tabla_sucursal.getEditorComponent();
                        aComp1.requestFocus();
                        break;

                    }

                }
                if (tabla > 0) {
                    break;

                }
            } catch (Exception e) {
            }
        }

        if (tabla > 0) {
            return;

        }
        
        tabla_almacen.editCellAt(0, 2);
        Component aComp1 = tabla_almacen.getEditorComponent();
        aComp1.requestFocus();
        for (int j = 0; j < tabla_almacen.getRowCount(); j++) {
            try {

                for (int i = 2; i < tabla_almacen.getColumnCount() - 2; i++) {
                    if (tabla_almacen.getValueAt(j, i).toString() == ("")) {
                        JOptionPane.showMessageDialog(rootPane, "HAY CAMPO VACIO:" + tabla_almacen.getTableHeader().getColumnModel().getColumn(i).getHeaderValue());
                        tabla = tabla + 1;
                        tabla_almacen.editCellAt(j, i);
                        Component aComp11 = tabla_almacen.getEditorComponent();
                        aComp11.requestFocus();
                        break;

                    } else if (tabla_almacen.getValueAt(j, i).toString().length() == 0) {
                        JOptionPane.showMessageDialog(rootPane, "HAY CAMPO VACIO:" + tabla_almacen.getTableHeader().getColumnModel().getColumn(i).getHeaderValue());
                        tabla = tabla + 1;
                        tabla_almacen.editCellAt(j, i);
                        Component aComp11 = tabla_almacen.getEditorComponent();
                        aComp11.requestFocus();
                        break;

                    }

                }
                if (tabla > 0) {
                    break;

                }
            } catch (Exception e) {
            }
        }

        if (tabla > 0) {
            return;

        }
        empresa = new Entity_Empresa(txtid_empresa.getText(), txtcod_empresa.getText(), txt_ruc.getText(), txt_razon_social.getText(),
                txt_razon_comercial.getText(), txt_direccion.getText(), txt_Descrip.getText(), box_estado.isSelected(), null);
          String respuesta=controller_empresa.Add_Empresa(empresa);
        //String respuesta = new Controller_Empresa().Add_Empresa(empresa);
        if (respuesta.equals("exito")) {
            if (txt_url.getText().length()>2) {
                String respuesta_imagen = new Controller_Empresa().guardarImagen(txt_url.getText(), txtid_empresa.getText());
            }
            
            for (int i = 0; i < tabla_sucursal.getRowCount(); i++) {
                sucursal = new Entity_Sucursal(
                        tabla_sucursal.getValueAt(i, 1).toString(), txtid_empresa.getText(),
                        tabla_sucursal.getValueAt(i, 3).toString(), tabla_sucursal.getValueAt(i, 4).toString(),
                        tabla_sucursal.getValueAt(i, 5).toString(), tabla_sucursal.getValueAt(i, 6).toString(),
                        tabla_sucursal.getValueAt(i, 7).toString(), tabla_sucursal.getValueAt(i, 8).toString()
                        );
                String respuesta_sucursal=new Controller_Empresa().Add_sucursal(sucursal);
            }
            
            for (int i = 0; i < tabla_almacen.getRowCount(); i++) {
                empresa = new Entity_Empresa(
                        tabla_almacen.getValueAt(i, 1).toString(), tabla_almacen.getValueAt(i, 2).toString(),
                        tabla_almacen.getValueAt(i, 3).toString(), txtid_empresa.getText(),
                        tabla_almacen.getValueAt(i, 5).toString()
                        );
                controller_empresa.Add_almacen(empresa);
               // String respuesta_sucursal=new Controller_Empresa().Add_almacen(empresa);
            }
            
        }
        
        

        controller_empresa.empresa(tabla_sucursal,TITLE_PROPERTY);
        controller_empresa.Almacen(tabla_almacen,TITLE_PROPERTY);
        limpiar();
        deshabilitar();
        txtcod_empresa.setText("");
        txtid_empresa.setText("");
        txtcod_empresa.setEnabled(true);
        txtcod_empresa.requestFocus();

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txtcod_empresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcod_empresaKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String id_usuario = new Controller_Empresa().Id_Empresa(txtcod_empresa.getText());
            if (id_usuario.equals("0")) {
                limpiar();
                habilitar();
                cargar_empresa(txtcod_empresa.getText());
                controller_empresa.empresa(tabla_sucursal,txtid_empresa.getText());
                controller_empresa.Almacen(tabla_almacen, txtid_empresa.getText());
                btn_guardar.setEnabled(true);
                //btn_eliminar.setEnabled(true);
                btn_cancelar.setEnabled(true);
                btn_editar.setEnabled(true);
                
            } else if (id_usuario.equals("fallo")) {

            } else {
                controller_empresa.empresa(tabla_sucursal,TITLE_PROPERTY);
                controller_empresa.Almacen(tabla_almacen, title);
                limpiar();
                habilitar();
                txtid_empresa.setText(id_usuario);
                btn_guardar.setEnabled(true);
                //btn_eliminar.setEnabled(true);
                btn_cancelar.setEnabled(true);
                btn_editar.setEnabled(false);

            }
            txtcod_empresa.setEnabled(false);
            txt_ruc.requestFocus();
            evt.consume();
        }

    }//GEN-LAST:event_txtcod_empresaKeyPressed

    private void txt_rucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rucKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_razon_social.requestFocus();
        }
    }//GEN-LAST:event_txt_rucKeyPressed

    private void txt_razon_socialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_razon_socialKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_razon_comercial.requestFocus();
        }
    }//GEN-LAST:event_txt_razon_socialKeyPressed

    private void txt_razon_comercialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_razon_comercialKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_direccion.requestFocus();
        }
    }//GEN-LAST:event_txt_razon_comercialKeyPressed

    private void txt_DescripKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DescripKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            box_estado.requestFocus();
        }
    }//GEN-LAST:event_txt_DescripKeyPressed

    private void txt_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_Descrip.requestFocus();
        }
    }//GEN-LAST:event_txt_direccionKeyPressed

    private void tabla_empresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_empresaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpiar();
            habilitar();
            cargar_empresa(tabla_empresa.getValueAt(tabla_empresa.getSelectedRow(), 1).toString());
            controller_empresa.empresa(tabla_sucursal,txtid_empresa.getText());
            controller_empresa.Almacen(tabla_almacen,txtid_empresa.getText());
            btn_guardar.setEnabled(true);
            //btn_eliminar.setEnabled(true);
            btn_cancelar.setEnabled(true);
            Dialog_empresa.dispose();
            txt_ruc.requestFocus();
            txtcod_empresa.setEnabled(false);
            btn_editar.setEnabled(true);
            evt.consume();
        }
    }//GEN-LAST:event_tabla_empresaKeyPressed

    private void btn_agregar_filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_filaActionPerformed
        // TODO add your handling code here:
        controller_empresa.add_sucursal(tabla_sucursal);
    }//GEN-LAST:event_btn_agregar_filaActionPerformed

    private void tabla_sucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_sucursalMouseClicked
        // TODO add your handling code here:
        controller_empresa.reset_variable();
        int fila = tabla_sucursal.rowAtPoint(evt.getPoint());
        int column = tabla_sucursal.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tabla_sucursal.getRowHeight();
        if (row < tabla_sucursal.getRowCount() && row >= 0 && column < tabla_sucursal.getColumnCount() && column >= 0) {
            Object value = tabla_sucursal.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btneliminar")) {

                    if (tabla_sucursal.getSelectedRow() != -1) {
                        /*DefaultTableModel model = (DefaultTableModel) tabla_productos_presentacion.getModel();
                        model.removeRow(tabla_productos_presentacion.getSelectedRow());*/
                        if (tabla_sucursal.getValueAt(fila, 1).toString().equals("")) {
                            DefaultTableModel model = (DefaultTableModel) tabla_sucursal.getModel();
                            model.removeRow(tabla_sucursal.getSelectedRow());
                        } else if (tabla_sucursal.getValueAt(fila, 1).toString().equals(null)) {
                            System.out.println("1");
                        } else {
                            if (controller_empresa.delete_sucursal(tabla_sucursal.getValueAt(tabla_sucursal.getSelectedRow(), 1).toString()).equals("exito")) {
                                DefaultTableModel model = (DefaultTableModel) tabla_sucursal.getModel();
                                model.removeRow(tabla_sucursal.getSelectedRow());
                            } else {
                                Function_ShowMessageDialog.ShowMessageDialogvalidacion(rootPane, "ERROR NO SE ELIMINO");
                            }
                           
                            
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "sss");
                    }

                }

            }
            if (value instanceof JCheckBox) {
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox) value;
                if (ch.isSelected() == true) {
                    ch.setSelected(false);
                }
                if (ch.isSelected() == false) {
                    ch.setSelected(true);
                }

            }
        }
    }//GEN-LAST:event_tabla_sucursalMouseClicked

    private void tabla_almacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_almacenMouseClicked
        // TODO add your handling code here:
        controller_empresa.reset_variable_almacen();
        int fila = tabla_almacen.rowAtPoint(evt.getPoint());
        int column = tabla_almacen.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tabla_almacen.getRowHeight();
        if (row < tabla_almacen.getRowCount() && row >= 0 && column < tabla_almacen.getColumnCount() && column >= 0) {
            Object value = tabla_almacen.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btneliminar")) {

                    if (tabla_almacen.getSelectedRow() != -1) {
                        /*DefaultTableModel model = (DefaultTableModel) tabla_productos_presentacion.getModel();
                        model.removeRow(tabla_productos_presentacion.getSelectedRow());*/
                        if (tabla_almacen.getValueAt(fila, 1).toString().equals("")) {
                            DefaultTableModel model = (DefaultTableModel) tabla_almacen.getModel();
                            model.removeRow(tabla_almacen.getSelectedRow());
                        } else if (tabla_almacen.getValueAt(fila, 1).toString().equals(null)) {
                            System.out.println("1");
                        } else {
                            if (controller_empresa.delete_almacen(tabla_almacen.getValueAt(tabla_almacen.getSelectedRow(), 1).toString()).equals("exito")) {
                                DefaultTableModel model = (DefaultTableModel) tabla_almacen.getModel();
                                model.removeRow(tabla_almacen.getSelectedRow());
                            } else {
                                Function_ShowMessageDialog.ShowMessageDialogvalidacion(rootPane, "ERROR NO SE ELIMINO");
                            }
                           
                            
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "sss");
                    }

                }

            }
            if (value instanceof JCheckBox) {
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox) value;
                if (ch.isSelected() == true) {
                    ch.setSelected(false);
                }
                if (ch.isSelected() == false) {
                    ch.setSelected(true);
                }

            }
        }
    }//GEN-LAST:event_tabla_almacenMouseClicked

    private void btn_agregar_fila_almacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_fila_almacenActionPerformed
        // TODO add your handling code here:
        
        controller_empresa.Add_Almacen(tabla_almacen, TITLE_PROPERTY);
    }//GEN-LAST:event_btn_agregar_fila_almacenActionPerformed
    void cargar_empresa(String cod_empresa) {
        try {
            List<Entity_Empresa> empresa = new Controller_Empresa().buscar_empresa(cod_empresa);
            txtid_empresa.setText(empresa.get(0).getEmpresa_id());
            txtcod_empresa.setText(empresa.get(0).getEmpresa_cod());
            txt_ruc.setText(empresa.get(0).getEmpresa_ruc());
            txt_razon_social.setText(empresa.get(0).getEmpresa_razon_social());
            txt_razon_comercial.setText(empresa.get(0).getEmpresa_comercial());
            txt_direccion.setText(empresa.get(0).getEmpresa_direccion());
            txt_Descrip.setText(empresa.get(0).getEmpresa_decrip());
            box_estado.setSelected(empresa.get(0).getEmpresa_estado());

            if (empresa.get(0).getEmpresa_imagen() == null) {
                Image foto = getToolkit().getImage("src\\Icon\\icon_subir_imagen.png");
                foto = foto.getScaledInstance(lbl_imagen.getWidth(), lbl_imagen.getHeight(), Image.SCALE_DEFAULT);
                lbl_imagen.setIcon(new ImageIcon(foto));
            } else {
                Blob blob = empresa.get(0).getEmpresa_imagen();
                byte[] data;

                data = blob.getBytes(1, (int) blob.length());

                BufferedImage img = null;
                try {
                    img = ImageIO.read(new ByteArrayInputStream(data));
                } catch (Exception e) {
                }

                lbl_imagen.setIcon(new ImageIcon(img.getScaledInstance(lbl_imagen.getWidth(), lbl_imagen.getHeight(), Image.SCALE_DEFAULT)));
            }
            

        } catch (SQLException ex) {
            Logger.getLogger(View_Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void habilitar() {
        txt_ruc.setEnabled(true);
        txt_razon_social.setEnabled(true);
        txt_razon_comercial.setEnabled(true);
        txt_direccion.setEnabled(true);
        txt_Descrip.setEnabled(true);
        box_estado.setEnabled(true);
        //txt_url.setEnabled(true);

    }

    void deshabilitar() {
        txt_ruc.setEnabled(false);
        txt_razon_social.setEnabled(false);
        txt_razon_comercial.setEnabled(false);
        txt_direccion.setEnabled(false);
        txt_Descrip.setEnabled(false);
        box_estado.setEnabled(false);
        txt_url.setEnabled(false);
        btn_guardar.setEnabled(false);
        //btn_eliminar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        btn_editar.setEnabled(false);

    }

    void limpiar() {
        txt_ruc.setText("");
        txt_razon_social.setText("");
        txt_razon_comercial.setText("");
        txt_direccion.setText("");
        txt_Descrip.setText("");
        box_estado.setSelected(true);
        txt_url.setText("");
        Image foto = getToolkit().getImage("src\\Icon\\icon_subir_imagen.png");
        foto = foto.getScaledInstance(lbl_imagen.getWidth(), lbl_imagen.getHeight(), Image.SCALE_DEFAULT);
        lbl_imagen.setIcon(new ImageIcon(foto));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_empresa;
    private javax.swing.JCheckBox box_estado;
    public static javax.swing.JButton btn_agregar_fila;
    public static javax.swing.JButton btn_agregar_fila_almacen;
    private javax.swing.JButton btn_busacr;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardar_imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_imagen;
    private javax.swing.JTable tabla_almacen;
    private javax.swing.JTable tabla_empresa;
    private javax.swing.JTable tabla_sucursal;
    private javax.swing.JTextField txt_Descrip;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_razon_comercial;
    private javax.swing.JTextField txt_razon_social;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txt_url;
    private javax.swing.JTextField txtcod_empresa;
    private javax.swing.JTextField txtid_empresa;
    // End of variables declaration//GEN-END:variables
}
